import type { Metadata } from "next";
import { Inter, Nabla } from "next/font/google";
import "./globals.css";
import Footer from "../components/components/footer";
import Navbar from "../components/components/navbar";
import { SearchProvider } from '../../context/SearchContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <SearchProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar></Navbar>
            {children}
          <Footer></Footer>
        </body>
      </html>
    </SearchProvider>
  );
}
